"""Capability routing, constraints, and worker fabrics."""
from __future__ import annotations

from hyai.capabilities.adapters import (
    AdapterError,
    DirectAccessForbiddenError,
    ModelAdapter,
    ProviderAdapter,
    ToolAdapter,
    verify_adapter_access,
)
from hyai.capabilities.resolver import (
    CapabilityPlan,
    CapabilityRequest,
    CapabilityResolver,
    ConstraintSatisfactionError,
    FallbackRecord,
    HardcodedModelIdentityError,
    ImplementationCandidate,
    ResolverError,
    SilentDowngradeForbiddenError,
)
from hyai.capabilities.spec import (
    CapabilityError,
    CapabilityParameter,
    CapabilitySpec,
    CapabilityValidationError,
    DynamicCapabilityManifest,
    QualityClass,
    RiskClass,
    create_capability_spec,
    validate_capability_spec_document,
)
from hyai.capabilities.worker import (
    DynamicDepartmentWorkerPool,
    LeaseExpiredError,
    ResourceLease,
    TrustClass,
    UnpermittedActionError,
    WorkerDescriptor,
    WorkerError,
    WorkerStatus,
    WorkerValidationError,
    create_resource_lease,
    create_worker_descriptor,
    validate_resource_lease_document,
    validate_worker_descriptor_document,
)

__all__ = [
    "AdapterError",
    "CapabilityError",
    "CapabilityParameter",
    "CapabilityPlan",
    "CapabilityRequest",
    "CapabilityResolver",
    "CapabilitySpec",
    "CapabilityValidationError",
    "ConstraintSatisfactionError",
    "DirectAccessForbiddenError",
    "DynamicCapabilityManifest",
    "DynamicDepartmentWorkerPool",
    "FallbackRecord",
    "HardcodedModelIdentityError",
    "ImplementationCandidate",
    "LeaseExpiredError",
    "ModelAdapter",
    "ProviderAdapter",
    "QualityClass",
    "ResourceLease",
    "ResolverError",
    "RiskClass",
    "SilentDowngradeForbiddenError",
    "ToolAdapter",
    "TrustClass",
    "UnpermittedActionError",
    "WorkerDescriptor",
    "WorkerError",
    "WorkerStatus",
    "WorkerValidationError",
    "create_capability_spec",
    "create_resource_lease",
    "create_worker_descriptor",
    "validate_capability_spec_document",
    "validate_resource_lease_document",
    "validate_worker_descriptor_document",
    "verify_adapter_access",
]
