"""Canonical Controlled Self-Evolution boundary."""
from hyai.evolution.canary import (
    CanaryExecutionError,
    CanaryPlan,
    EvolutionRolloutManager,
    PrematurePromotionError,
    UpgradeProvenanceRecord,
    create_canary_plan,
    validate_canary_plan_document,
)
from hyai.evolution.proposal import (
    EvolutionError,
    EvolutionProposal,
    HiddenNegativeEvidenceError,
    MisclassifiedTierError,
    PromotionApproval,
    SelfPromotionForbiddenError,
    StaleApprovalError,
    UnapprovedPromotionError,
    UpgradeLifecycleState,
    UpgradeProposal,
    UpgradeTier,
    create_evolution_proposal,
    create_promotion_approval,
    create_upgrade_proposal,
    validate_evolution_proposal_document,
    validate_promotion_approval_document,
    validate_upgrade_proposal_document,
)

__all__ = [
    "CanaryExecutionError",
    "CanaryPlan",
    "EvolutionError",
    "EvolutionProposal",
    "EvolutionRolloutManager",
    "HiddenNegativeEvidenceError",
    "MisclassifiedTierError",
    "PrematurePromotionError",
    "PromotionApproval",
    "SelfPromotionForbiddenError",
    "StaleApprovalError",
    "UnapprovedPromotionError",
    "UpgradeLifecycleState",
    "UpgradeProposal",
    "UpgradeProvenanceRecord",
    "UpgradeTier",
    "create_canary_plan",
    "create_evolution_proposal",
    "create_promotion_approval",
    "create_upgrade_proposal",
    "validate_canary_plan_document",
    "validate_evolution_proposal_document",
    "validate_promotion_approval_document",
    "validate_upgrade_proposal_document",
]
