"""Canonical Observability and FinOps boundary."""
from hyai.observability.finops import (
    BudgetChecker,
    BudgetEnvelope,
    BudgetExceededError,
    CostRecord,
    FinOpsError,
    UnallocatedCostError,
    create_budget_envelope,
    validate_budget_envelope_document,
)
from hyai.observability.lifecycle import (
    LifecycleError,
    SignalLifecycleState,
    SignalSeverity,
    SignalType,
    TechnologyLifecycleEntry,
    TechLifecycleState,
    UpgradeSignal,
    create_technology_lifecycle_entry,
    create_upgrade_signal,
    validate_technology_lifecycle_entry_document,
    validate_upgrade_signal_document,
)
from hyai.observability.telemetry import (
    CorrelationError,
    ObservabilityError,
    SLOBreachError,
    SLOEvaluation,
    SLOSpec,
    StructuredLogRecord,
    StructuredMetricRecord,
    TraceContext,
    evaluate_slo_compliance,
)

__all__ = [
    "BudgetChecker",
    "BudgetEnvelope",
    "BudgetExceededError",
    "CorrelationError",
    "CostRecord",
    "FinOpsError",
    "LifecycleError",
    "ObservabilityError",
    "SLOBreachError",
    "SLOEvaluation",
    "SLOSpec",
    "SignalLifecycleState",
    "SignalSeverity",
    "SignalType",
    "StructuredLogRecord",
    "StructuredMetricRecord",
    "TechnologyLifecycleEntry",
    "TechLifecycleState",
    "TraceContext",
    "UnallocatedCostError",
    "UpgradeSignal",
    "create_budget_envelope",
    "create_technology_lifecycle_entry",
    "create_upgrade_signal",
    "evaluate_slo_compliance",
    "validate_budget_envelope_document",
    "validate_technology_lifecycle_entry_document",
    "validate_upgrade_signal_document",
]
